Upgrade Play, ReactiveMongo and update the code
* upgrade Play to version 2.4.2
* upgrade Play-ReactiveMongo to version 0.11.4.play24
* bump version of the project to 0.11.1
* suppress deprecation about cursor method
* remove the ImplicitBSONHandlers import to fix compilation errors:

```
[error] reactivemongo-demo-app/app/controllers/Articles.scala:64: No Json serializer as JsObject found for type play.api.libs.json.JsObject. Try to implement an implicit OWrites or OFormat for this type.
[error]     val found = collection.find(query).cursor[Article]
[error]                                ^
[error] reactivemongo-demo-app/app/controllers/Articles.scala:83: No Json serializer as JsObject found for type play.api.libs.json.JsObject. Try to implement an implicit OWrites or OFormat for this type.
[error]     val futureArticle = collection.find(Json.obj("_id" -> id)).one[Article]
[error]                                        ^
[error] reactivemongo-demo-app/app/controllers/Articles.scala:138: type mismatch;
[error]  found   : reactivemongo.bson.BSONDateTime
[error]  required: play.api.libs.json.Json.JsValueWrapper
[error]             "updateDate" -> BSONDateTime(new DateTime().getMillis),
[error]                                         ^
[error] reactivemongo-demo-app/app/controllers/Articles.scala:151: No Json serializer as JsObject found for type play.api.libs.json.JsObject. Try to implement an implicit OWrites or OFormat for this type.
[error]     gridFS.find[JsObject, JSONReadFile](Json.obj("article" -> id)).
[error]                                        ^
[error] reactivemongo-demo-app/app/controllers/Articles.scala:179: No Json serializer as JsObject found for type play.api.libs.json.JsObject. Try to implement an implicit OWrites or OFormat for this type.
[error]           gridFS.files.update(
[error]                              ^
[error] reactivemongo-demo-app/app/controllers/Articles.scala:194: No Json serializer as JsObject found for type play.api.libs.json.JsObject. Try to implement an implicit OWrites or OFormat for this type.
[error]     val file = gridFS.find[JsObject, JSONReadFile](Json.obj("_id" -> id))
[error]                                                   ^
[error] reactivemongo-demo-app/app/controllers/Articles.scala:205: No implicit view available from (String, play.api.libs.json.JsValue) => reactivemongo.bson.Producer[reactivemongo.bson.BSONElement].
[error]     gridFS.remove(Json toJson id).map(_ => Ok).
[error]                  ^
[error] 7 errors found
```